version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: calendar
      POSTGRES_PASSWORD: calendar
      POSTGRES_DB: calendar
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  dbdata: {}
