spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/calendar
    username: calendar
    password: calendar
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    locations: classpath:db/migration
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
cors:
  allowed-origins:
    - http://localhost:5173
    - https://your-gh-pages-host
telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:}
